---
title: "My Week 6 in MB612"
author: "Hanalei"
date: "2024-10-01"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fig.path = "../Week 06/Output/")
```

# Intro to Penguins. 
today, we are working w/ penguin data to *learn* **R Markdown**

# Load Libraries
```{r}
library(tidyverse)
library(here)
library(cowplot)
library(lubridate)
library(rmarkdown)
library(tinytex)
library(palmerpenguins)
library(kableExtra)
```

# Inspect data
```{r}
glimpse(penguins)
```

# Bill length by *sex* plot
```{r penguin_bill_l,fig.cap="Length of penguin bills by sex in three different species" , echo=FALSE}
ggplot(data=penguins%>%drop_na(), 
       mapping = aes(x = species,
                     y = bill_length_mm,
                     color = sex))+
  geom_boxplot(lwd=1.2)+
  theme_classic(base_size=8)+
  xlab("Bill Depth (mm)")+ylab("Bill Length (mm)")+
  scale_color_manual(values=c("orange2","grey15"))
```
# Bill length table
