---
title: "Week_9_classwork"
author: "Hanalei"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      error = FALSE)
```

```{r}
library(here)
library(tidyverse)
library(tidytext)
library(wordcloud2)
library(janeaustenr)
library(palmerpenguins)
library(PNWColors)
```

```{r}
df <- tibble(
  a = rnorm(10), # draws 10 random values from a normal distribution
  b = rnorm(10),
  c = rnorm(10),
  d = rnorm(10)
)
head(df)
```

```{r}
df<-df %>%
  mutate(a = (a-min(a, na.rm = TRUE))/(max(a, na.rm = TRUE)-min(a, na.rm = TRUE)))%>%
  mutate(b = (b-min(b, na.rm = TRUE))/(max(b, na.rm = TRUE)-min(b, na.rm = TRUE)))%>%
  mutate(c = (c-min(c, na.rm = TRUE))/(max(c, na.rm = TRUE)-min(c, na.rm = TRUE)))%>%
  mutate(a = (d-min(d, na.rm = TRUE))/(max(d, na.rm = TRUE)-min(d, na.rm = TRUE)))
```

```{r}
rescale01<- function(x) {
  value<-(x-min(x, na.rm = TRUE))/max(x, na.rm = TRUE)-min(x, na.rm=TRUE)
return=value
}

df %>%
  mutate(a = rescale01(a),
         b = rescale01(b),
         c = rescale01(c),
         d = rescale01(d))
```

```{r}
f_to_c <- function(temp_F) {
  temp_c <- (temp_F - 32)*5/9
  return(temp_c)
}

f_to_c(69)

c_to_k <- function(temp_c) {
  temp_k <- temp_c+273.15
  return(temp_k)
}

c_to_k(0)
```

```{r}
myplot <- function(data, x ,y) {
pal<-pnw_palette("Starfish",3, type = "discrete") #the color palette


ggplot(data, aes(x = {{x}}, y = {{y}}, color = island))+
  geom_point()+
  geom_smooth(method = "lm")+ # add a linear model
  scale_color_manual("Island", values=pal)+   # use pretty colors and another example of how to manually change the legend title for colors
  theme_bw()
}

myplot(data = penguins, x = body_mass_g, y = bill_length_mm)


my_p_plot <- function(data=penguins, x ,y) {
pal<-pnw_palette("Starfish",3, type = "discrete") #the color palette


ggplot(data, aes(x = {{x}}, y = {{y}}, color = island))+
  geom_point()+
  geom_smooth(method = "lm")+ # add a linear model
  scale_color_manual("Island", values=pal)+   # use pretty colors and another example of how to manually change the legend title for colors
  theme_bw()
}

my_p_plot(x = body_mass_g, y = bill_length_mm)
```

```{r}
#if-else

a <- 4
b <- 5

if (a > b) { # my question
  f <- 20 # if it is true give me answer 1
    } else { # else give me answer 2
  f <- 10
    }

f

#bringing into our plot ^
myplot<-function(data = penguins, x, y ,lines=TRUE ){ # add new argument for lines
pal<-pnw_palette("Lake",3, type = "discrete") # my color palette 

if(lines==TRUE){
ggplot(data, aes(x = {{x}}, y = {{y}} , color = island))+
  geom_point()+
  geom_smooth(method = "lm")+ # add a linear model
  scale_color_manual("Island", values=pal)+   # use pretty colors and change the legend title
  theme_bw()
}
else{
ggplot(data, aes(x = {{x}}, y = {{y}} , color = island))+
  geom_point()+
  scale_color_manual("Island", values=pal)+   # use pretty colors and change the legend title
  theme_bw()
}
}
myplot(x = body_mass_g, y = flipper_length_mm)
```

