---
title: "week_9_hw#2"
author: "Hanalei"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      error = FALSE)
```

```{r}
library(tidyverse)
library(here)
library(janitor)
```


```{r}
intertidal<-read_csv(here("Week_09","data", "intertidaldata.csv"))
lats<-read_csv(here("Week_09","data", "intertidaldata_latitude.csv"))
```


```{r}
plot<-intertidal%>%
  clean_names()%>% #clean that ish up
  select(site, quadrat, whelks_counts)%>% #selet these columns
  group_by(site,quadrat)%>% 
  summarise(total=sum(whelks_counts))%>% #count up all the whelks
  rename(tide=quadrat)%>% #rename quadrat to tide
  mutate(tide = str_extract(tide, "Low|Mid|High"))%>% #get rid of all funky misspellings
  mutate(tide = str_trim(tide))

  
  plot%>%
  ggplot(aes(x = total, y = site, fill = factor(tide, levels = c("Low", "Mid", "High")))) + #factor tide names so that we can order them how we want
  geom_col(position = "dodge") +  # Use dodge to separate bars by tide
  scale_fill_manual(values = c("Low" = "#A8D8E6", "Mid" = "#007C92", "High" = "#003D5B")) + #colors
  labs(title = "Whelks Count by Site and Tide Level",
       x = "Whelks Count",
       y = "Site",
       fill = "Tide Level") +
  theme_minimal()+
  theme(
    panel.grid.major = element_blank(),  # Remove major grid lines
    panel.grid.minor = element_blank()  # Remove minor grid lines
  )
  
  ggsave(here("Week_09", "output", "whelk_plot_duefriday.png")) 
  
```
